variable "env" {}
variable "instance_type" {}
variable "instance_names" {}
variable "key_name" {}
variable "amis" {}
variable "region" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "sg_id" {}